% =====================================================================
% Sun -- a Prolog realization of:
% https://bergholt.net/sun
%
% 3 nouns x 3 verbs x 4 adverbs x 2 syntactic orders = 72
% One variant for each eclipse in Saros 126 (1179-2459).
%
% Github source: https://github.com/bergholt/triptych - MIT license.
% Feel free to use for your own projects.
% =====================================================================

% --- Paradigm: noun ---

noun(apertures).
noun(auguries).
noun(apparitions).

% --- Paradigm: verb ---

verb(align).
verb(thicken).
verb(emerge).

% --- Paradigm: adverb ---

adverb(rhythmically).
adverb(vertically).
adverb(recursively).
adverb(now).

% --- Combination rule ---

variant(O, N, V, A) :-
    member(O, [0, 1]),
    noun(N),
    verb(V),
    adverb(A).

% --- Enumeration ---

run :-
    findall((O,N,V,A), variant(O,N,V,A), List),
    print_list(List, 1).

print_list([], _).
print_list([H|T], I) :-
    format('~d. ', [I]),
    print_variant(H),
    nl,
    NextI is I + 1,
    print_list(T, NextI).

print_variant((0, N, V, A)) :-
    format('~w ~w ~w', [N, V, A]).
print_variant((1, N, V, A)) :-
    format('~w, ~w ~w', [A, N, V]).

:- initialization(run, main).

% =====================================================================
% Why Prolog?
%
% Prolog is the only mainstream language built on declarative logic
% rather than imperative procedure. You state facts and relations;
% the system derives consequences. This is exactly Hjelmslev's method:
% a system is a network of relations, not a sequence of operations.
% The 72 variants of the poem are not generated by Prolog; they are
% proved. Each is a logical consequence of the underlying paradigmatic
% axes. The poem and the language share one grammar.
% =====================================================================
%
% Copenhagen, 2026
